name: Hourly Discord Webhook

# Runs at the top of every hour (UTC). Add workflow_dispatch for manual trigger.
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Send Discord webhook message
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Optional: override default message
          # MESSAGE: "Custom hourly update"
        run: |
          echo "Sending message to Discord webhook (URL is masked)." 
          python send_webhook.py
